export const BUTTONS = {
  ua: {
    SETTING: 'Налаштування⚙️',
    ACCEPT: 'OK',
    SUPPORT: '💸Підтримка проєкту💸',
    YEARS: '✅Обрати цей рік:',
    MONTHS: '✅Обрати цей місяць:',
    DETAILS: '📝Детальніше',
    BALANCE: 'Баланс 💰',
    TRANSACTIONS: 'Транзакції 💸',
    STATISTICS: 'Статистика 📊',
    FAMILY: 'Родина👨‍👩‍👧‍👧',
    LANGUAGE: 'Оберіть мову📝',
    RESET: '⛔️Видалити  усі данні🗑️',
    INCOME: 'Надходження 💹',
    EXPENSE: 'Витрати 🛍️',
    DELETE_LAST: 'Видалення останніх️❌',
    TODAY: 'За сьогодні🗓️',
    WEEK: 'За тиждень🗓️',
    MONTH: 'За місяць🗓️',
    SELECT_MONTH: 'Оберіть місяць📤️',
    MY_INCOME: 'Надходження💵',
    MY_EXPENSE: 'Витрати🧾',
    BY_CATEGORY: 'За категорією🗃️',
    JANUARY: 'Січень ❄️',
    FEBRUARY: 'Лютий ☃️',
    MARCH: 'Березень 🌷',
    APRIL: 'Квітень 🌸',
    MAY: 'Травень 🌱',
    JUNE: 'Червень 🌞',
    JULY: 'Липень 🌻',
    AUGUST: 'Серпень 🌞',
    SEPTEMBER: 'Вересень 🍂',
    OCTOBER: 'Жовтень 🎃',
    NOVEMBER: 'Листопад 🍁',
    DECEMBER: 'Грудень 🎄',
    YES: 'ТАК✅',
    NO: 'НІ❌',
    GET_ID: 'Отримати 🆔',
    CREATE_GROUP: 'Створити родину👩‍❤️‍👨',
    ADD_TO_GROUP: 'Додати до родини👨‍👩‍👧‍👧',
    DELETE_FROM_GROUP: '❌Видалити родину❌',
    HELP: 'Допомога⛑️',
    AGREE: 'Згоден✅',
    DISAGREE: 'Не згоден❌',
    BACK: '↩️Повернутися',
    SELECT_YEAR: 'Оберіть дату🗓️',
  },
  en: {
    SETTING: 'Settings⚙️',
    ACCEPT: 'OK',
    SUPPORT: '💸Project support💸',
    YEARS: '✅Select this year:',
    MONTHS: '✅Select this month:',
    DETAILS: '📝More details',
    BALANCE: 'Balance 💰',
    TRANSACTIONS: 'Transactions 💸',
    STATISTICS: 'Statistics 📊',
    FAMILY: 'Family👨‍👩‍👧‍👧',
    LANGUAGE: 'Choose a language📝',
    RESET: '⛔️Delete all data🗑️',
    INCOME: 'Income 💹',
    EXPENSE: 'Expenses 🛍️',
    DELETE_LAST: 'Delete Last❌',
    TODAY: 'For Today🗓️',
    WEEK: 'Last Week🗓️',
    MONTH: 'Last Month🗓️',
    SELECT_MONTH: 'Select Month📤️',
    MY_INCOME: 'My Incomes💵',
    MY_EXPENSE: 'My Expenses🧾',
    BY_CATEGORY: 'By Category🗃️',
    JANUARY: 'January ❄️',
    FEBRUARY: 'February ☃️',
    MARCH: 'March 🌷',
    APRIL: 'April 🌸',
    MAY: 'May 🌱',
    JUNE: 'June 🌞',
    JULY: 'July 🌻',
    AUGUST: 'August 🌞',
    SEPTEMBER: 'September 🍂',
    OCTOBER: 'October 🎃',
    NOVEMBER: 'November 🍁',
    DECEMBER: 'December 🎄',
    YES: 'YES✅',
    NO: 'NO❌',
    GET_ID: 'Get 🆔',
    CREATE_GROUP: 'Create Family👩‍❤️‍👨',
    ADD_TO_GROUP: 'Add to Family👨‍👩‍👧‍👧',
    DELETE_FROM_GROUP: '❌Remove Family❌',
    HELP: 'Help⛑️',
    AGREE: 'Agree✅',
    DISAGREE: 'Disagree❌',
    BACK: '↩️Back',
    SELECT_YEAR: 'Selected date🗓️',
  },
};
