export const BUTTONS = {
  ua: {
    SETTING: 'Налаштування⚙️',
    ACCEPT: 'OK',
    SUPPORT: '💸Підтримка проєкту💸',
    YEARS: '✅Обрати цей рік:',
    MONTHS: '✅Обрати цей місяць:',
    DETAILS: '📝Детальніше',
    BALANCE: 'Баланс 💰',
    TRANSACTIONS: 'Транзакції 💸',
    STATISTICS: 'Статистика 📊',
    FAMILY: 'Родина👨‍👩‍👧‍👧',
    LANGUAGE: 'Оберіть мову📝',
    RESET: '⛔️Видалити  усі данні🗑️',
    INCOME: 'Надходження 💹',
    EXPENSE: 'Витрати 🛍️',
    DELETE_LAST: 'Видалення останніх️❌',
    TODAY: 'За сьогодні🗓️',
    WEEK: 'За тиждень🗓️',
    MONTH: 'За місяць🗓️',
    SELECT_MONTH: 'Оберіть місяць📤️',
    MY_INCOME: 'Надходження💵',
    MY_EXPENSE: 'Витрати🧾',
    BY_CATEGORY: 'За категорією🗃️',
    JANUARY: 'Січень ❄️',
    FEBRUARY: 'Лютий ☃️',
    MARCH: 'Березень 🌷',
    APRIL: 'Квітень 🌸',
    MAY: 'Травень 🌱',
    JUNE: 'Червень 🌞',
    JULY: 'Липень 🌻',
    AUGUST: 'Серпень 🌞',
    SEPTEMBER: 'Вересень 🍂',
    OCTOBER: 'Жовтень 🎃',
    NOVEMBER: 'Листопад 🍁',
    DECEMBER: 'Грудень 🎄',
    YES: 'ТАК✅',
    NO: 'НІ❌',
    GET_ID: 'Отримати 🆔',
    CREATE_GROUP: 'Створити родину👩‍❤️‍👨',
    ADD_TO_GROUP: 'Додати до родини👨‍👩‍👧‍👧',
    DELETE_FROM_GROUP: '❌Видалити родину❌',
    HELP: 'Допомога⛑️',
    AGREE: 'Згоден✅',
    DISAGREE: 'Не згоден❌',
    BACK: '↩️Повернутися',
    SELECT_YEAR: 'Оберіть дату🗓️',
    GET_PREMIUM: '🏆Преміум🏆(test)',
    SET_PREMIUM: 'Отримати преміум💸',
    DAY_PREMIUM: 'Днів залишилось🗓️',
    TRIAL_PREMIUM: 'Отримати пробні 14 днів✅',
    CURRENCY: 'Курс валют💸',
    CRYPTO: 'Курс крипто 🪙',
    PREMIUM_GPT: 'GPT можливості',
    COMPARED: 'Додати до порівняння',
    GET_COMPARED: 'Отримати порівняння',
    SEE_COMPARED: 'Подивитися що порівнюємо',
    DELL_COMPARED: 'Видалити порівняння🗑️',
    PREMIUM_BUTTON: '🌟Преміум меню🌟',
    GET_FAMILY: `Хто в родині`,
    DIAGRAM: `Отримати диграму📊`,
    TOP10: `Топ10 ваших транзакцій🔝`,
    TOP10GRAPH: `Отримати графік ваших Топ10`,
    ADVSTAT: `Просунута статистика💪`,
    INFO: `Інформація ℹ️`,
    FIN: `Фінаносва грамотність`,
  },
  en: {
    SETTING: 'Settings⚙️',
    ACCEPT: 'OK',
    SUPPORT: '💸Project support💸',
    YEARS: '✅Select this year:',
    MONTHS: '✅Select this month:',
    DETAILS: '📝More details',
    BALANCE: 'Balance 💰',
    TRANSACTIONS: 'Transactions 💸',
    STATISTICS: 'Statistics 📊',
    FAMILY: 'Family👨‍👩‍👧‍👧',
    LANGUAGE: 'Choose a language📝',
    RESET: '⛔️Delete all data🗑️',
    INCOME: 'Income 💹',
    EXPENSE: 'Expenses 🛍️',
    DELETE_LAST: 'Delete Last❌',
    TODAY: 'For Today🗓️',
    WEEK: 'Last Week🗓️',
    MONTH: 'Last Month🗓️',
    SELECT_MONTH: 'Select Month📤️',
    MY_INCOME: 'My Incomes💵',
    MY_EXPENSE: 'My Expenses🧾',
    BY_CATEGORY: 'By Category🗃️',
    JANUARY: 'January ❄️',
    FEBRUARY: 'February ☃️',
    MARCH: 'March 🌷',
    APRIL: 'April 🌸',
    MAY: 'May 🌱',
    JUNE: 'June 🌞',
    JULY: 'July 🌻',
    AUGUST: 'August 🌞',
    SEPTEMBER: 'September 🍂',
    OCTOBER: 'October 🎃',
    NOVEMBER: 'November 🍁',
    DECEMBER: 'December 🎄',
    YES: 'YES✅',
    NO: 'NO❌',
    GET_ID: 'Get 🆔',
    CREATE_GROUP: 'Create Family👩‍❤️‍👨',
    ADD_TO_GROUP: 'Add to Family👨‍👩‍👧‍👧',
    DELETE_FROM_GROUP: '❌Remove Family❌',
    HELP: 'Help⛑️',
    AGREE: 'Agree✅',
    DISAGREE: 'Disagree❌',
    BACK: '↩️Back',
    SELECT_YEAR: 'Selected date🗓️',
    GET_PREMIUM: '🏆Premium🏆(test)',
    SET_PREMIUM: 'Set premium💸',
    DAY_PREMIUM: 'Days left🗓️',
    TRIAL_PREMIUM: 'Get a 14-day trial✅',
    CURRENCY: 'Exchange rate💸',
    CRYPTO: 'Rate of crypto🪙',
    PREMIUM_GPT: 'GPT opportunities',
    COMPARED: 'Add to compare',
    GET_COMPARED: 'Get a comparison',
    SEE_COMPARED: 'See what we compare',
    DELL_COMPARED: 'Remove comparison🗑️',
    PREMIUM_BUTTON: '🌟Premium menu🌟',
    GET_FAMILY: `Who's in the group`,
    DIAGRAM: `Get a diagram📊`,
    TOP10: `Your top 10 transactions🔝`,
    TOP10GRAPH: `Get a graph of your Top10`,
    ADVSTAT: `💪Advanced statistics`,
    INFO: `Information ℹ️`,
    FIN: `Financial literacy`,
  },
  pl: {
    SETTING: 'Ustawienia⚙️',
    ACCEPT: 'OK',
    SUPPORT: '💸Wsparcie projektu💸',
    YEARS: '✅Wybierz ten rok:',
    MONTHS: '✅Wybierz ten miesiąc:',
    DETAILS: '📝Więcej szczegółów',
    BALANCE: 'Saldo 💰',
    TRANSACTIONS: 'Transakcje 💸',
    STATISTICS: 'Statystyki 📊',
    FAMILY: 'Rodzina👨‍👩‍👧‍👧',
    LANGUAGE: 'Wybierz język📝',
    RESET: '⛔️Usuń wszystkie dane🗑️',
    INCOME: 'Dochody 💹',
    EXPENSE: 'Wydatki 🛍️',
    DELETE_LAST: 'Usuń ostatnie❌',
    TODAY: 'Na dzisiaj🗓️',
    WEEK: 'Ostatni tydzień🗓️',
    MONTH: 'Ostatni miesiąc🗓️',
    SELECT_MONTH: 'Wybierz miesiąc📤️',
    MY_INCOME: 'Moje dochody💵',
    MY_EXPENSE: 'Moje wydatki🧾',
    BY_CATEGORY: 'Według kategorii🗃️',
    JANUARY: 'Styczeń ❄️',
    FEBRUARY: 'Luty ☃️',
    MARCH: 'Marzec 🌷',
    APRIL: 'Kwiecień 🌸',
    MAY: 'Maj 🌱',
    JUNE: 'Czerwiec 🌞',
    JULY: 'Lipiec 🌻',
    AUGUST: 'Sierpień 🌞',
    SEPTEMBER: 'Wrzesień 🍂',
    OCTOBER: 'Październik 🎃',
    NOVEMBER: 'Listopad 🍁',
    DECEMBER: 'Grudzień 🎄',
    YES: 'TAK✅',
    NO: 'NIE❌',
    GET_ID: 'Pobierz 🆔',
    CREATE_GROUP: 'Stwórz rodzinę👩‍❤️‍👨',
    ADD_TO_GROUP: 'Dodaj do rodziny👨‍👩‍👧‍👧',
    DELETE_FROM_GROUP: '❌Usuń rodzinę❌',
    HELP: 'Pomoc⛑️',
    AGREE: 'Zgadzam się✅',
    DISAGREE: 'Nie zgadzam się❌',
    BACK: '↩️Powrót',
    SELECT_YEAR: 'Wybrana data🗓️',
    GET_PREMIUM: '🏆Premium🏆(test)',
    SET_PREMIUM: 'Ustaw premium💸',
    DAY_PREMIUM: 'Pozostałe dni🗓️',
    TRIAL_PREMIUM: 'Otrzymaj 14-dniowy okres próbny✅',
    CURRENCY: 'Kurs wymiany💸',
    CRYPTO: 'Kurs kryptowaluty🪙',
    PREMIUM_GPT: 'Możliwości GPT',
    COMPARED: 'Dodaj do porównania',
    GET_COMPARED: 'Pobierz porównanie',
    SEE_COMPARED: 'Zobacz, co porównujemy',
    DELL_COMPARED: 'Usuń porównanie🗑️',
    PREMIUM_BUTTON: '🌟Menu premium🌟',
    GET_FAMILY: `Kto jest w rodzinie`,
    DIAGRAM: `Pobierz diagram📊`,
    TOP10: `Top 10 twoich transakcji🔝`,
    TOP10GRAPH: `Pobierz wykres swoich Top10`,
    ADVSTAT: `💪Zaawansowane statystyki`,
    INFO: `Informacje ℹ️`,
    FIN: `Umiejętność finansowa`,
  },
};
