export const BUTTONS = {
  ua: {
    BALANCE: 'Баланс 💰',
    TRANSACTIONS: 'Транзакції 💸',
    STATISTICS: 'Статистика 📊',
    FAMILY: 'Родина👨‍👩‍👧‍👧(у розробці)',
    INCOME: 'Надходження 💹',
    EXPENSE: 'Витрати 🛍️',
    DELETE_LAST: 'Видалення останніх️❌',
    TODAY: 'За сьогодні',
    WEEK: 'За тиждень🗓️',
    MONTH: 'За місяць🗓️',
    SELECT_MONTH: 'Вибрати місяць📤️',
    MY_INCOME: 'Мої надходження💵',
    MY_EXPENSE: 'Мої витрати🧾',
    BY_CATEGORY: 'За категорією🗃️',
    JANUARY: 'Січень',
    FEBRUARY: 'Лютий',
    MARCH: 'Березень',
    APRIL: 'Квітень',
    MAY: 'Травень',
    JUNE: 'Червень',
    JULY: 'Липень',
    AUGUST: 'Серпень',
    SEPTEMBER: 'Вересень',
    OCTOBER: 'Жовтень',
    NOVEMBER: 'Листопад',
    DECEMBER: 'Грудень',
    YES: 'ТАК✅',
    NO: 'НІ❌',
  },
  en: {
    BALANCE: 'Balance 💰',
    TRANSACTIONS: 'Transactions 💸',
    STATISTICS: 'Statistics 📊',
    FAMILY: 'Family👨‍👩‍👧‍👧(in development)',
    INCOME: 'Income 💹',
    EXPENSE: 'Expenses 🛍️',
    DELETE_LAST: 'Delete Last❌',
    TODAY: 'For Today',
    WEEK: 'Last Week🗓️',
    MONTH: 'Last Month🗓️',
    SELECT_MONTH: 'Select Month📤️',
    MY_INCOME: 'My Incomes💵',
    MY_EXPENSE: 'My Expenses🧾',
    BY_CATEGORY: 'By Category🗃️',
    JANUARY: 'January',
    FEBRUARY: 'February',
    MARCH: 'March',
    APRIL: 'April',
    MAY: 'May',
    JUNE: 'June',
    JULY: 'July',
    AUGUST: 'August',
    SEPTEMBER: 'September',
    OCTOBER: 'October',
    NOVEMBER: 'November',
    DECEMBER: 'December',
    YES: "YES✅",
    NO: "NO❌"
  },
};
