export const FAMILY_TEXT = {
  ua: {
    FAMILY_MENU: '🔽Родинне меню спочатку скористуйтесь :🔽 ',
    YOUR_ID: 'Твій 🆔:',
    GROUP_CREATED: 'Група створена, ваш 🆔 додано',
    ENTER_USER_ID: 'Будь ласка, введіть 🆔 користувача, якого ви хочете додати до групи.',
    INVITE_SENT: 'Запрошення відправлено користувачу з 🆔',
    ID_ALREADY_EXISTS: 'ID вже є у групі',
    INVITATION_ACCEPTED: 'Ви прийняли запрошення від користувача з 🆔',
    INVITATION_DECLINED: 'Ви відхилили запрошення ',
    INVITATION_TEXT: 'Вас було запрошено до групи користувачем. Приймаєте?',
    GROUP_DELETED: 'Групу успішно видалено🗑️',
    GROUP_EMPTY: 'Група вже порожня або не існує',
    INVALID_INPUT: '❌Невірні данні❌'
  },
  en: {
    FAMILY_MENU: '🔽Family menu use first:🔽 ',
    YOUR_ID: 'Your 🆔:',
    GROUP_CREATED: 'Group created, your 🆔 has been added',
    ENTER_USER_ID: 'Please enter the user 🆔 you want to add to the group.',
    INVITE_SENT: 'Invitation sent to user with 🆔',
    ID_ALREADY_EXISTS: 'ID already exists in the group',
    INVITATION_ACCEPTED: 'You have accepted the invitation from the user with 🆔',
    INVITATION_DECLINED: 'You have declined the invitation',
    INVITATION_TEXT: 'You have been invited to the group by a user. Do you accept',
    GROUP_DELETED: 'Group successfully deleted🗑️',
    GROUP_EMPTY: 'The group is already empty or does not exist',
    INVALID_INPUT: '❌Invalid input❌',
  },
};
